# Generated by Django 3.1.5 on 2021-02-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='send_date',
        ),
    ]
