# Generated by Django 3.1.5 on 2021-02-04 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0002_remove_emailmessage_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 16, 23, 50, 927447), verbose_name='Дата создания'),
        ),
    ]
