# Generated by Django 3.1.5 on 2021-02-04 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0003_emailmessage_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 16, 32, 34, 110712), verbose_name='Дата создания'),
        ),
    ]
