# Generated by Django 3.1.5 on 2021-02-04 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0004_auto_20210204_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 16, 37, 37, 164007), verbose_name='Дата отправки'),
        ),
    ]
