# Generated by Django 3.1.5 on 2021-02-12 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0006_auto_20210209_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 12, 11, 49, 39, 701058), verbose_name='Дата отправки'),
        ),
    ]
