# Generated by Django 3.1.5 on 2021-02-12 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0007_auto_20210212_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 12, 11, 44, 31, 606902), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 12, 11, 52, 51, 606902), verbose_name='Дата отправки'),
        ),
    ]
