# Generated by Django 3.1.5 on 2021-02-12 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0008_auto_20210212_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 12, 12, 9, 1, 808266), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 12, 12, 17, 21, 808266), verbose_name='Дата отправки'),
        ),
    ]
