# Generated by Django 3.1.6 on 2021-02-12 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0010_auto_20210212_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 12, 21, 15, 41, 82789), verbose_name='Дата отправки'),
        ),
    ]
