# Generated by Django 3.1.6 on 2021-02-13 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0015_auto_20210213_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 15, 53, 12, 696710), verbose_name='Дата отправки'),
        ),
    ]
